using System.Text.Json;
using CDArchive.Core.Models;

namespace CDArchive.Core.Tests.Canon;

/// <summary>
/// Regression tests for display-node types (SubpieceDisplayNode, PieceOriginalNode,
/// VersionDisplayNode), RoleEntry serialization, CanonPiece.TreeChildren, and
/// computed piece/composer properties.
/// </summary>
public class CanonModelDisplayTests
{
    // ── SubpieceDisplayNode ──────────────────────────────────────────────────

    [Fact]
    public void SubpieceDisplayNode_Default_ExpandableWhenPieceHasSubpieces()
    {
        var piece = new CanonPiece
        {
            Title = "Allegro",
            Subpieces = [new CanonPiece { Title = "Part A" }]
        };
        var node = new SubpieceDisplayNode(piece);
        Assert.True(node.HasChildren);
        Assert.NotNull(node.Children);
        Assert.Single(node.Children!);
    }

    [Fact]
    public void SubpieceDisplayNode_Default_NotExpandableWhenNoSubpieces()
    {
        var node = new SubpieceDisplayNode(new CanonPiece { Title = "Allegro" });
        Assert.False(node.HasChildren);
        Assert.Null(node.Children);
    }

    [Fact]
    public void SubpieceDisplayNode_IsExpandableFalse_SuppressesExpanderEvenWithSubpieces()
    {
        var piece = new CanonPiece
        {
            Title = "Allegro",
            Subpieces = [new CanonPiece { Title = "Part A" }]
        };
        var node = new SubpieceDisplayNode(piece, isExpandable: false);
        Assert.False(node.HasChildren);
        Assert.Null(node.Children);
    }

    [Fact]
    public void SubpieceDisplayNode_FilteredChildren_UsedInsteadOfAutoGenerated()
    {
        var piece = new CanonPiece
        {
            Title = "Allegro",
            Subpieces = [new CanonPiece { Title = "Auto-Part" }]
        };
        var overrideChild = new SubpieceDisplayNode(new CanonPiece { Title = "Override-Part" });
        var node = new SubpieceDisplayNode(piece, filteredChildren: [overrideChild]);

        Assert.True(node.HasChildren);
        var children = node.Children!;
        Assert.Single(children);
        Assert.Equal("Override-Part", children[0].Piece.Title);
    }

    [Fact]
    public void SubpieceDisplayNode_AutoChildren_WrapSubpiecesAsDisplayNodes()
    {
        var piece = new CanonPiece
        {
            Title = "Sonata",
            Subpieces =
            [
                new CanonPiece { Title = "Allegro" },
                new CanonPiece { Title = "Andante" },
            ]
        };
        var node = new SubpieceDisplayNode(piece);
        var children = node.Children!;
        Assert.Equal(2, children.Count);
        Assert.Equal("Allegro", children[0].Piece.Title);
        Assert.Equal("Andante", children[1].Piece.Title);
    }

    // ── PieceOriginalNode ────────────────────────────────────────────────────

    [Fact]
    public void PieceOriginalNode_Default_ExpandableWhenPieceHasSubpieces()
    {
        var piece = new CanonPiece
        {
            Subpieces = [new CanonPiece { Title = "Movement 1" }]
        };
        var node = new PieceOriginalNode(piece);
        Assert.True(node.HasChildren);
        Assert.NotNull(node.Children);
    }

    [Fact]
    public void PieceOriginalNode_IsExpandableFalse_SuppressesExpander()
    {
        var piece = new CanonPiece
        {
            Subpieces = [new CanonPiece { Title = "Movement 1" }]
        };
        var node = new PieceOriginalNode(piece, isExpandable: false);
        Assert.False(node.HasChildren);
        Assert.Null(node.Children);
    }

    [Fact]
    public void PieceOriginalNode_FilteredChildren_UsedInsteadOfAutoGenerated()
    {
        var piece = new CanonPiece
        {
            Subpieces = [new CanonPiece { Title = "Auto" }]
        };
        var overrideChild = new SubpieceDisplayNode(new CanonPiece { Title = "Override" });
        var node = new PieceOriginalNode(piece, filteredChildren: [overrideChild]);

        var children = node.Children!;
        Assert.Single(children);
        Assert.Equal("Override", children[0].Piece.Title);
    }

    [Fact]
    public void PieceOriginalNode_DisplayTitle_IsAlwaysOriginal()
    {
        var node = new PieceOriginalNode(new CanonPiece { Title = "Something else" });
        Assert.Equal("Original", node.DisplayTitle);
    }

    // ── VersionDisplayNode ───────────────────────────────────────────────────

    [Fact]
    public void VersionDisplayNode_Default_ExpandableWhenVersionHasSubpieces()
    {
        var version = new CanonPieceVersion
        {
            Description = "Orchestra",
            Subpieces = [new CanonPiece { Title = "Promenade" }]
        };
        var node = new VersionDisplayNode(version);
        Assert.True(node.HasSubpieces);
        Assert.NotNull(node.Children);
    }

    [Fact]
    public void VersionDisplayNode_IsExpandableFalse_SuppressesExpanderEvenWithSubpieces()
    {
        var version = new CanonPieceVersion
        {
            Description = "Orchestra",
            Subpieces = [new CanonPiece { Title = "Promenade" }]
        };
        var node = new VersionDisplayNode(version, isExpandable: false);
        Assert.False(node.HasSubpieces);
        Assert.Null(node.Children);
    }

    [Fact]
    public void VersionDisplayNode_FilteredChildren_UsedInsteadOfAutoGenerated()
    {
        var version = new CanonPieceVersion
        {
            Description = "Orchestra",
            Subpieces = [new CanonPiece { Title = "Auto" }]
        };
        var overrideChild = new SubpieceDisplayNode(new CanonPiece { Title = "Override" });
        var node = new VersionDisplayNode(version, filteredChildren: [overrideChild]);

        Assert.True(node.HasSubpieces);
        var children = node.Children!;
        Assert.Single(children);
        Assert.Equal("Override", children[0].Piece.Title);
    }

    [Fact]
    public void VersionDisplayNode_DisplayTitle_PrefixedWithVersion()
    {
        var node = new VersionDisplayNode(new CanonPieceVersion { Description = "Chamber" });
        Assert.Equal("Version: Chamber", node.DisplayTitle);
    }

    // ── CanonPiece.TreeChildren ──────────────────────────────────────────────

    [Fact]
    public void TreeChildren_PieceWithVersions_ReturnsOriginalNodePlusVersionNodes()
    {
        var piece = new CanonPiece
        {
            Title = "Symphony",
            Versions =
            [
                new CanonPieceVersion { Description = "Original" },
                new CanonPieceVersion { Description = "Revised" },
            ]
        };

        var children = piece.TreeChildren!;
        Assert.Equal(3, children.Count);
        Assert.IsType<PieceOriginalNode>(children[0]);
        Assert.IsType<VersionDisplayNode>(children[1]);
        Assert.IsType<VersionDisplayNode>(children[2]);
    }

    [Fact]
    public void TreeChildren_PieceWithSubpiecesOnly_ReturnsSubpieceDisplayNodes()
    {
        var piece = new CanonPiece
        {
            Title = "Sonata",
            Subpieces =
            [
                new CanonPiece { Title = "Allegro" },
                new CanonPiece { Title = "Andante" },
            ]
        };

        var children = piece.TreeChildren!;
        Assert.Equal(2, children.Count);
        Assert.All(children.Cast<object>(), c => Assert.IsType<SubpieceDisplayNode>(c));
    }

    [Fact]
    public void TreeChildren_PlainPiece_ReturnsNull()
    {
        var piece = new CanonPiece { Title = "Song" };
        Assert.Null(piece.TreeChildren);
        Assert.False(piece.HasTreeChildren);
    }

    [Fact]
    public void HasTreeChildren_PieceWithVersions_ReturnsTrue()
    {
        var piece = new CanonPiece
        {
            Versions = [new CanonPieceVersion { Description = "Original" }]
        };
        Assert.True(piece.HasTreeChildren);
    }

    // ── RoleEntry parsing ────────────────────────────────────────────────────

    [Fact]
    public void ParseRoles_StringItems_ParsedWithNameOnly()
    {
        // Regression: an earlier bug silently dropped string-format role references
        var json = JsonDocument.Parse("[\"Florestan\", \"Leonore\"]").RootElement;
        var roles = RoleEntry.ParseRoles(json);

        Assert.Equal(2, roles.Count);
        Assert.Equal("Florestan", roles[0].Name);
        Assert.Equal("Leonore", roles[1].Name);
        Assert.Null(roles[0].VoiceType);
        Assert.Null(roles[1].VoiceType);
    }

    [Fact]
    public void ParseRoles_ObjectItems_ParsedWithAllFields()
    {
        var json = JsonDocument.Parse(
            "[{\"name\":\"Florestan\",\"voice_type\":\"tenor\",\"description\":\"A prisoner\"}]")
            .RootElement;
        var roles = RoleEntry.ParseRoles(json);

        var role = Assert.Single(roles);
        Assert.Equal("Florestan", role.Name);
        Assert.Equal("tenor", role.VoiceType);
        Assert.Equal("A prisoner", role.Description);
    }

    [Fact]
    public void ParseRoles_MixedItems_BothFormatsParsed()
    {
        var json = JsonDocument.Parse(
            "[{\"name\":\"Florestan\",\"voice_type\":\"tenor\"}, \"Leonore\"]")
            .RootElement;
        var roles = RoleEntry.ParseRoles(json);

        Assert.Equal(2, roles.Count);
        Assert.Equal("tenor", roles[0].VoiceType);
        Assert.Null(roles[1].VoiceType);
    }

    [Fact]
    public void ParseRoles_NonArrayElement_ReturnsEmpty()
    {
        var json = JsonDocument.Parse("{}").RootElement;
        var roles = RoleEntry.ParseRoles(json);
        Assert.Empty(roles);
    }

    // ── RoleEntry serialisation ──────────────────────────────────────────────

    [Fact]
    public void SerializeRoles_NameOnlyEntries_EmittedAsPlainStrings()
    {
        // Regression: an earlier bug always emitted objects even for name-only entries
        var roles = new List<RoleEntry>
        {
            new() { Name = "Florestan" },
            new() { Name = "Leonore" },
        };
        var json = RoleEntry.SerializeRoles(roles)!.Value;
        var raw = json.GetRawText();

        // Should be plain JSON strings, not objects
        Assert.Contains("\"Florestan\"", raw);
        Assert.DoesNotContain("\"name\"", raw);
    }

    [Fact]
    public void SerializeRoles_FullEntries_EmittedAsObjects()
    {
        var roles = new List<RoleEntry>
        {
            new() { Name = "Florestan", VoiceType = "tenor", Description = "A prisoner" }
        };
        var json = RoleEntry.SerializeRoles(roles)!.Value;
        var raw = json.GetRawText();

        Assert.Contains("\"name\"", raw);
        Assert.Contains("\"voice_type\"", raw);
        Assert.Contains("\"description\"", raw);
    }

    [Fact]
    public void SerializeRoles_EmptyList_ReturnsNull()
    {
        Assert.Null(RoleEntry.SerializeRoles([]));
    }

    [Fact]
    public void SerializeRoles_RoundTrip_PreservesData()
    {
        var original = new List<RoleEntry>
        {
            new() { Name = "Florestan", VoiceType = "tenor" },
            new() { Name = "Leonore" },    // name-only → string format
        };
        var json = RoleEntry.SerializeRoles(original)!.Value;
        var reparsed = RoleEntry.ParseRoles(json);

        Assert.Equal(2, reparsed.Count);
        Assert.Equal("Florestan", reparsed[0].Name);
        Assert.Equal("tenor", reparsed[0].VoiceType);
        Assert.Equal("Leonore", reparsed[1].Name);
        Assert.Null(reparsed[1].VoiceType);
    }

    // ── Subpiece numbering ───────────────────────────────────────────────────

    [Fact]
    public void EffectiveSubpiecesNumbered_OperaCategory_DefaultsFalse()
    {
        var piece = new CanonPiece { InstrumentationCategory = "Opera" };
        Assert.False(piece.EffectiveSubpiecesNumbered);
    }

    [Fact]
    public void EffectiveSubpiecesNumbered_OrchestraCategory_DefaultsTrue()
    {
        var piece = new CanonPiece { InstrumentationCategory = "Orchestra" };
        Assert.True(piece.EffectiveSubpiecesNumbered);
    }

    [Fact]
    public void EffectiveSubpiecesNumbered_ExplicitFalseOverride_OverridesCategory()
    {
        var piece = new CanonPiece
        {
            InstrumentationCategory = "Orchestra",
            NumberedSubpieces = false
        };
        Assert.False(piece.EffectiveSubpiecesNumbered);
    }

    [Fact]
    public void EffectiveSubpiecesNumbered_ExplicitTrueOverride_OverridesOpera()
    {
        var piece = new CanonPiece
        {
            InstrumentationCategory = "Opera",
            NumberedSubpieces = true
        };
        Assert.True(piece.EffectiveSubpiecesNumbered);
    }

    // ── Catalog / key formatting ─────────────────────────────────────────────

    [Fact]
    public void Catalog_SingleOpusEntry_FormatsCorrectly()
    {
        var piece = new CanonPiece
        {
            CatalogInfo = [new CatalogInfo { Catalog = "Op.", CatalogNumber = "67" }]
        };
        Assert.Equal("Op. 67", piece.Catalog);
    }

    [Fact]
    public void Catalog_WithSubnumber_IncludesHashSubnumber()
    {
        var piece = new CanonPiece
        {
            CatalogInfo =
            [
                new CatalogInfo { Catalog = "Op.", CatalogNumber = "27", CatalogSubnumber = "2" }
            ]
        };
        Assert.Contains("Op. 27", piece.Catalog);
        Assert.Contains("#2", piece.Catalog);
    }

    [Fact]
    public void Catalog_MultipleEntries_FormatsAll()
    {
        var piece = new CanonPiece
        {
            CatalogInfo =
            [
                new CatalogInfo { Catalog = "Op.", CatalogNumber = "27" },
                new CatalogInfo { Catalog = "WoO", CatalogNumber = "50" },
            ]
        };
        // Catalog returns only the FIRST entry (used for tree column display)
        Assert.Equal("Op. 27", piece.Catalog);
    }

    [Fact]
    public void Catalog_NoCatalogInfo_ReturnsEmpty()
    {
        var piece = new CanonPiece { Title = "Song" };
        Assert.Equal("", piece.Catalog);
    }

    [Fact]
    public void Key_MajorKey_ReturnsTonalityAsIs()
    {
        // Major keys return the tonality unchanged (capitalised), no "major" suffix
        var piece = new CanonPiece { KeyTonality = "C", KeyMode = "major" };
        Assert.Equal("C", piece.Key);
    }

    [Fact]
    public void Key_MinorKey_ReturnsTonalityLowercased()
    {
        // Minor keys return the tonality in lower-case, no "minor" suffix
        var piece = new CanonPiece { KeyTonality = "C-sharp", KeyMode = "minor" };
        Assert.Equal("c-sharp", piece.Key);
    }

    [Fact]
    public void Key_NoKeySet_ReturnsEmpty()
    {
        var piece = new CanonPiece { Title = "Untitled" };
        Assert.Equal("", piece.Key);
    }

    // ── CanonComposer computed properties ────────────────────────────────────

    [Fact]
    public void BirthYear_FromFullIsoDate_ExtractsYear()
    {
        var composer = new CanonComposer { BirthDate = "1770-12-17" };
        Assert.Equal("1770", composer.BirthYear);
    }

    [Fact]
    public void DeathYear_FromFullIsoDate_ExtractsYear()
    {
        var composer = new CanonComposer { DeathDate = "1827-03-26" };
        Assert.Equal("1827", composer.DeathYear);
    }

    [Fact]
    public void LifeSpan_BothDates_FormatsRange()
    {
        var composer = new CanonComposer
        {
            BirthDate = "1770-12-17",
            DeathDate = "1827-03-26"
        };
        var span = composer.LifeSpan;
        Assert.Contains("1770", span);
        Assert.Contains("1827", span);
    }

    [Fact]
    public void BirthLocation_CityAndCountry_IncludesBoth()
    {
        var composer = new CanonComposer
        {
            BirthPlace = "Bonn",
            BirthCountry = "Germany"
        };
        var location = composer.BirthLocation;
        Assert.Contains("Bonn", location);
        Assert.Contains("Germany", location);
    }
}
